version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    networks:
      - app-network
    environment:
      SYMFONY_ENV: dev
    depends_on:
      - db
      - web

  db:
    image: mysql:5.7
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: symfony_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: